version: '3.8'

services:
  spotify_utils:
    build: ./app
    command: python spotify_utils.py
    volumes:
      - ./config.hjson:/home/app/config.hjson:ro
      - ./data/:/home/app/data/
      - auth:/home/app/auth/
    restart: unless-stopped

volumes:
  auth:
