version: '3.8'

services:
  spotify_utils:
    build: ./app
    command: python spotify_utils.py
    volumes:
      - ./config.hjson:/home/app/config.hjson:ro
      - spotify_utils_data:/home/app/data/
    restart: unless-stopped

volumes:
  spotify_utils_data:
